version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodbc
    environment:
      MONGO_INITDB_ROOT_USERNAME: licenta2024
      MONGO_INITDB_ROOT_PASSWORD: licenta2024
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

